customCommands:
  - key: "<c-f>"
    command: "git fetch --prune origin"
    context: "remotes"
  - key: "<c-r>"
    command: "git reset --soft HEAD~1"
    context: "localBranches"
  - key: "<c-n>"
    command: "git reset --hard"
    context: "localBranches"
gui:
  # stuff relating to the UI
  theme:
    activeBorderColor:
      - "#e6b450"
      - bold
    inactiveBorderColor:
      - "#aad94c"
    searchingActiveBorderColor:
      - "#39bae6"
      - bold
    optionsTextColor:
      - "#8e959e"
    selectedLineBgColor:
      - "#272c36"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#8e959e"
    cherryPickedCommitBgColor:
      - "#39bae6"
    markedBaseCommitFgColor:
      - "#39bae6"
    markedBaseCommitBgColor:
      - "#d95757"
    unstagedChangesColor:
      - "#d95757"
    defaultFgColor:
      - "#d1d1c7"
  scrollHeight: 2 # how many lines you scroll by
  scrollPastBottom: true # enable scrolling past the bottom
  sidePanelWidth: 0.3333 # number from 0 to 1
  expandFocusedSidePanel: false
  mainPanelSplitMode: "flexible" # one of 'horizontal' | 'flexible' | 'vertical'
  language: "auto" # one of 'auto' | 'en' | 'zh' | 'pl' | 'nl'
  # theme:
  #   activeBorderColor:
  #     - "#662300"
  #     - bold
  #   inactiveBorderColor:
  #     - "#85523b"
  #   searchingActiveBorderColor:
  #     - "#6a5f11"
  #     - bold
  #   optionsTextColor:
  #     - "#56423a"
  #   selectedLineBgColor:
  #     - "#56423a"
  #   inactiveViewSelectedLineBgColor:
  #     - bold
  #   cherryPickedCommitFgColor:
  #     - "#56423a"
  #   cherryPickedCommitBgColor:
  #     - "#6a5f11"
  #   markedBaseCommitFgColor:
  #     - "#6a5f11"
  #   markedBaseCommitBgColor:
  #     - "#ba1a1a"
  #   unstagedChangesColor:
  #     - "#ba1a1a"
  #   defaultFgColor:
  #     - "#231915"
  commitLength:
    show: false
  mouseEvents: true
  skipDiscardChangeWarning: false
  skipStashWarning: false
  showFileTree: true # for rendering changes files in a tree format
  showListFooter: false # for seeing the '5 of 20' message in list panels
  showRandomTip: false
  showCommandLog: false
  commandLogSize: 8
git:
  commitPrefixes:
    nautilus: # This is repository folder name
      - pattern: "^(\\d+).*"
        replace: "[#$1] "
